### ISSUE TITLE
guix package: error:  unknown package

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/guix.install#3]
Dear @rekado,

I am running into some issues when trying to install this package: https://github.com/nx10/httpgd

```r
> guix.install("httpgd")

Starting download of /tmp/guix-file.1Ov63H
From http://cran.r-project.org/src/contrib/httpgd_1.3.0.tar.gz...
 …3.0.tar.gz  383KiB                  1.4MiB/s 00:00 [##################] 100.0%
The following package will be installed:
   r-httpgd 1.3.0

guix package: error: c++17: unknown package
```

I am assuming that Guix is interpreting the `C++17` [SystemRequirements]( https://github.com/nx10/httpgd/blob/f44dae0885f60a7d04dab382c70191406690bf49/DESCRIPTION#L38-L39) as required  package.

Best,
Alex

**Comment by rekado** [comment]
Correct assessment!  We have a list of known "invalid packages" in guix/import/cran.scm.  I've just added a few more strings in Guix commit 7d6843b6314fbee784ea1550a91dd54cd46f7428.

**Comment by alexg9010** [comment]
Hi @rekado. Unfortunately, there seems to be another thing to catch: 

```
r$> guix.install("httpgd")

Starting download of /tmp/guix-file.q1HQbk
From http://cran.r-project.org/src/contrib/httpgd_1.3.0.tar.gz...
 …3.0.tar.gz  383KiB                      0B/s 00:00 [                  ]   0
 …3.0.tar.gz  383KiB                  602KiB/s 00:00 [###               ]  16
 …3.0.tar.gz  383KiB                  1.3MiB/s 00:00 [##################] 100.0%
The following package will be installed:
   r-httpgd 1.3.0

guix package: error: freetype2: unknown package
```

When running `guix import cran httpgd -r -s specification > ~/manifests/httpgd.scm` and changing `freetype2` to `freetype`, I am able to load the package in `guix shell -f ~/manifests/httpgd.scm`. 

Best,
Alex

**Comment by rekado** [comment]
Added a mapping from `freetype2` to `freetype` as it is called in Guix with commit 4073f43cbc2a9e0a5156ff5f950973871bff49e3.
