### ISSUE TITLE
Error when installing from git repos (github,  gitlab,...)

### ISSUE THREAD

**Issue by JVAQUEROM** [BIMSBbioinfo/guix.install#5]
When I try to install packages from a git repo (github, gitlab) it works ok, but when it is going to start building I get this error:

```
guix package: error: while setting up the build environment: getting attribute
s of path `/etc/services': No such file or directory
```

I am pretty new to guix so I may be doing something wrong. Here I paste everything I get when trying to do this with `lubridate`  package (as test, because it works with CRAN version):

```
guix.install::guix.install("https://github.com/tidyverse/lubridate")
Se actualizará el siguiente paquete:
   r-lubridate 1.8.0 → 1.9.3.9000-1.e0b50c1

The following derivations will be built:
  /gnu/store/jxcqbzlmdcfh4cx9hn6riga9vjk5yx1p-r-lubridate-1.9.3.9000-1.e0b50c1.d
rv
  /gnu/store/dk0ir50x5bnr9qa2mwk4014xw5z6adm8-r-lubridate-1.9.3.9000-1.e0b50c1-c
heckout.drv
  /gnu/store/f7pgx5k66628jhkwm4hsh2zn0b8cgmm4-r-timechange-0.3.0.drv

guix package: error: while setting up the build environment: getting attributes 
of path `/etc/services': No such file or directory
Error in guix.install::guix.install("https://github.com/tidyverse/lubridate") : 
  Failed to install imported package        r-lubridate

```

**Comment by rekado** [comment]
Thanks for the bug report.  Could you tell me what GNU+Linux distribution you are using?  Please also tell me what version of Guix you are on (`guix describe`).

**Comment by JVAQUEROM** [comment]
The distribution is opensuse Tumbleweed.

```
 → LANG=C guix describe
Generation 11   May 08 2024 23:19:25    (current)
  guix-cran 8a462f0
    repository URL: https://github.com/guix-science/guix-cran.git
    branch: master
    commit: 8a462f08926a413ae762d153b82371b33d07f839
  guix 7b7f299
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 7b7f299bb493e485c5534b8c554e51d4f3a8c026
```

**Comment by JVAQUEROM** [comment]
In another computer with CentOS I can install with guix.install but then when I close the R terminal the package is not found. However, if I run again the guix.install it says that it will update the package and then says "nothing to do" (obviously no need to update). After that, I can load the package. But if I close the R terminal, I have to run again the guix.install for R to find the package. What could that be?

EDIT: I found out that guix.install uses .LibPaths() to add the path to the new library, so I checked the values and changed my R_LIBS environment variable accordingly. It is curious it is using two /gnu/store/.... folders, not sure why.

**Comment by JVAQUEROM** [comment]
Regarding the original problem, I found  that in opensuse, `/etc/services` is in `/usr/etc/services` so I just did a symlink and it worked properly (`ln -s /usr/etc/services /etc/services`). Regards.

**Comment by rekado** [comment]
> In another computer with CentOS I can install with guix.install but then when I close the R terminal the package is not found. However, if I run again the guix.install it says that it will update the package and then says "nothing to do" (obviously no need to update). After that, I can load the package. But if I close the R terminal, I have to run again the guix.install for R to find the package. What could that be?
> 
> EDIT: I found out that guix.install uses .LibPaths() to add the path to the new library, so I checked the values and changed my R_LIBS environment variable accordingly. It is curious it is using two /gnu/store/.... folders, not sure why.

Sorry for the late response (I'm on leave for a few months).  Guix records the R_LIBS_SITE variable in the generated `etc/profile` file whenever R is installed.  `guix.install` cannot use `etc/profile` (because that's for evaluation in a shell), so it uses `.libPaths` to add the `site-library` directory of the profile to which it installed R packages.
